---
title: "data_aggregation"
output: html_document
date: "2023-02-15"
---

## Cleaning environment
```{r}
rm(list=ls())
```

```{r}
# Load packages
install.packages("tidyverse")
library(tidyverse)

install.packages("lubridate")
library(lubridate)
```
## Importing the data
```{r}
all_turbine = read.csv(file.choose(),header=T)
```

## Making the column time_interval a time object
```{r }
# R doesn't know start_date and end_date are dates - they were read in as numeric
# convert those both to date objects
all_turbine$Time = ymd_hms(all_turbine$Time)
```

## Rounding the time_interval column to "10 minutes"
```{r}
all_turbine$interval_time = round_date(all_turbine$Time, "10 mins")
````

## merging data frames
```{r}
ims_and_oil = merge(new_ims_bearing_temp_all, new_oil_temp, by.x = c('Group.1', 'Group.2'), by.y = c('Group.1', 'Group.2'))
show(ims_and_oil)
````

## changing colounm names
```{r}
colnames(ims_and_oil)[1] <- 'TimeStamp'
colnames(ims_and_oil)[2] <- 'TurbineName'
colnames(ims_and_oil)[3] <- 'IMS Bearing Temp'
colnames(ims_and_oil)[4] <- 'Oil Temp'

```




